config/routes.rb
Cvongo::Application.routes.draw do
  
  resources :societies

  resources :localities

  resources :cities

  resources :accounts

  devise_for :users
  get "welcome/index"
  get "welcome/sync"

  root 'welcome#index'

end

app/models/society.rb
class Society < ActiveRecord::Base
end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
  before_action :set_society, only: [:show, :edit, :update, :destroy]

  # GET /societies
  # GET /societies.json
  def index
    @societies = Society.all
  end

  # GET /societies/1
  # GET /societies/1.json
  def show
  end

  # GET /societies/new
  def new
    @society = Society.new
  end

  # GET /societies/1/edit
  def edit
  end

  # POST /societies
  # POST /societies.json
  def create
    @society = Society.new(society_params)

    respond_to do |format|
      if @society.save
        format.html { redirect_to @society, notice: 'Society was successfully created.' }
        format.json { render action: 'show', status: :created, location: @society }
      else
        format.html { render action: 'new' }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /societies/1
  # PATCH/PUT /societies/1.json
  def update
    respond_to do |format|
      if @society.update(society_params)
        format.html { redirect_to @society, notice: 'Society was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /societies/1
  # DELETE /societies/1.json
  def destroy
    @society.destroy
    respond_to do |format|
      format.html { redirect_to societies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_society
      @society = Society.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def society_params
      params.require(:society).permit(:name, :locality_id)
    end
end

app/helpers/societies_helper.rb
module SocietiesHelper
end

app/views/societies/_form.html.erb
<%= form_for(@society) do |f| %>
  <% if @society.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@society.errors.count, "error") %> prohibited this society from being saved:</h2>

      <ul>
      <% @society.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :locality_id %><br>
    <%= f.number_field :locality_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/societies/edit.html.erb
<h1>Editing society</h1>

<%= render 'form' %>

<%= link_to 'Show', @society %> |
<%= link_to 'Back', societies_path %>

app/views/societies/index.html.erb
<h1>Listing societies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Locality</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @societies.each do |society| %>
      <tr>
        <td><%= society.name %></td>
        <td><%= society.locality_id %></td>
        <td><%= link_to 'Show', society %></td>
        <td><%= link_to 'Edit', edit_society_path(society) %></td>
        <td><%= link_to 'Destroy', society, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Society', new_society_path %>

app/views/societies/new.html.erb
<h1>New society</h1>

<%= render 'form' %>

<%= link_to 'Back', societies_path %>

app/views/societies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @society.name %>
</p>

<p>
  <strong>Locality:</strong>
  <%= @society.locality_id %>
</p>

<%= link_to 'Edit', edit_society_path(@society) %> |
<%= link_to 'Back', societies_path %>